version: '3'

services:
  db:
    image: postgres:9.6
    # ports:
    #   - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
  app:
    image: stores
    build:
      context: .
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "3031:3031"
    environment:
      DATABASE_URL: postgres://postgres:passw0rd@db:5432/postgres
    # depends_on:
    #   - db

volumes:
  pg_data: {}
  pg_backups: {}